version: "3.7"

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: skimo-pl
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - skimo-pl-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - skimo-pl-redis:/var/lib/redis/data

  skimo-pl:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./skimo-pl
        target: /opt/app/skimo-pl
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./skimo-pl
        target: /opt/app/skimo-pl
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - skimo-pl
    ports:
      - '8020:8020'

volumes:
  skimo-pl-postgres:
  skimo-pl-redis:
